spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: amanda
    password: dbpass
  messages:
      always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
      basename: classpath:i18n/titles, classpath:i18n/messages", classpath:i18n/errors, classpath:i18n/validation # Comma-separated list of basenames, each following the ResourceBundle convention.
      cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
      encoding: UTF-8 # Message bundles encoding.
      fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.

server:
  port: 8080
